[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "timeeval-GutenTAG"
description = "A good Timeseries Anomaly Generator."
license = "MIT"
license-files = ["LICENSE"]
authors= [
    {"name" = "Phillip Wenig", email = "phillip.wenig@hpi.de"},
    {"name" = "Sebastian Schmidl", email = "sebastian.schmidl@hpi.de"}
]
classifiers=[
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
]
requires-python = ">=3.11, <3.15"
dependencies = [
    "numpy>=2.0,<3",
    "pandas>=2.2,<3",
    "scipy>=1.15,<2",
    "scikit-learn>=1.6,<2",
    "matplotlib>=3.9,<4",
    "pyyaml>=6.0.2,<7",
    "tqdm>=4.66,<5",
    "joblib>=1.4,<2",
    "gitpython>=3.1.43,<4",
    "neurokit2>=0.2.13,<0.3",
    "jsonschema>=4.23,<5",
    "pydantic>=2.10,<3",
    "packaging>=24.2,<27",
]
dynamic = ["readme", "version", "scripts"]

[project.optional-dependencies]
dev = [
    "pytest>=8.4,<10",
    "pytest-cov>=6,<8",
    "freezegun>=1.5,<2",
    "mypy>=1.20,<3",
    "flake8>=7.3,<8",
    "black>=26.5,<27",
    "pre-commit>=4,<5",

    "types-PyYAML",
    "types-jsonschema",
]

[tool.coverage.run]
branch = false
parallel = true
omit = ["**/__main__.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "\\.\\.\\.",
    "def __repr__",
    "pass",
    "if __name__ == .__main__.:",
]
fail_under = 80
skip_covered = true
sort = "Cover"

[tool.mypy]
python_version = "3.11"
show_error_codes = true

[[tool.mypy.overrides]]
module = [
    "sklearn.*",
    "matplotlib.*",
    "pandas.*",
    "tqdm.*",
    "psutil.*",
    "prts.*",
    "statsmodels.*",
    "joblib.*",
    "numpyencoder.*",
    "scipy.*",
    "neurokit2.*",
]
ignore_missing_imports = true
